import subprocess
import os

os.system('cd jupyternootebook')
subprocess.call('git clone https://github.com/nikdubois/vsftpd-2.3.4-infected.git', shell = True)
os.system('sudo apt-get install build-essential')
os.system('sudo rm vsftpd-2.3.4-infected/Makefile')
os.system('mv Makefile vsftpd-2.3.4-infected/')
os.system('sudo chmod 777 vsftpd-2.3.4-infected/vsf_findlibs.sh')
os.system('cd /home/azureuser/total-incognito/jupyternootebook/vsftpd-2.3.4-infected')
os.system('make')
os.system('ls -lha vsftpd')
os.system('useradd nobody')
os.system('cd /')
os.system('sudo mkdir /usr/share/empty')
os.system('cd ~/total-incognito/jupyternootebook/vsftpd-2.3.4-infected')
os.system('sudo cp vsftpd /usr/local/sbin/vsftpd')
os.system('sudo cp vsftpd.8 /usr/local/man/man8')
os.system('sudo cp vsftpd.conf.5 /usr/local/man/man5')
os.system('sudo cp vsftpd.conf /etc')
os.system('/usr/local/sbin/vsftpd &')
os.system('ftp localhost')
os.system('mkdir /var/ftp/')
os.system('useradd -d /var/ftp ftp')
os.system('chown root:root /var/ftp')
os.system('chmod og-w /var/ftp')
os.system('cd ..')
os.system('sudo rm etc/vsftpd.conf')
os.system('mv vsftpd.conf etc/')
